# Site settings

title: wonderland.js
encoding: UTF-8

collections:
  - posts

defaults:
  - scope:
      path: ""
      type: "post"
    values:
      layout: "presentation"
  - scope:
      path: ""
      type: "welcome"
    values:
      layout: "welcome"

sass:
    sass-dir: _sass
